force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C - {0000}</displayFormat>
        <label>Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/CommentText__c.field-meta.xml
<CustomField>
    <fullName>CommentText__c</fullName>
    <label>CommentText</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Related To</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommentsController.cls
public class CommentsController {
    @AuraEnabled(cacheable=false)
    public static String createCommentRecord(String commentText, Id relatedToID) {
        try {
            List<Comment__c > commentList = new List<Comment__c >();
            Comment__c  comment = new Comment__c ();
            comment.CommentText__c = commentText;
            comment.Related_To__c  = relatedToID;
        	commentList.add(comment);
            
            insert commentList;
            
            return 'Comment Saved@success@Saved your comment successfully';
        } catch (Exception ex) {
            return 'Opps !@error@ Could not save your comment';
        } finally {
            
        }
	}
    
    @AuraEnabled(cacheable=true)
    public static List<Comment__c> getCommentRecords(Id relatedToID) {
    	return [SELECT ID, Name, CommentText__c, CreatedDate FROM Comment__c WHERE Related_To__c  =: relatedToID ORDER BY CreatedDate DESC];

	}
    
    
    
    private class CommentWrapper {
        private String commentText;
        private Id relatedToId;
    }
}